# Generated by Django 5.0.1 on 2024-02-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='clothes_images', verbose_name='Картинка')),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'Xl')], default='L', max_length=150, verbose_name='Размер')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('som', 'Som'), ('dollar', 'Dollar'), ('euro', 'Euro')], default='som', max_length=150, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежды',
            },
        ),
    ]
