# Generated by Django 5.0.1 on 2024-02-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='currency',
            field=models.CharField(choices=[('C', 'Som'), ('$', 'Dollar'), ('€', 'Euro')], default='C', max_length=150, verbose_name='Валюта'),
        ),
    ]
