# Generated by Django 5.0.1 on 2024-02-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothes_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='old_price',
            field=models.IntegerField(default=0, verbose_name='Старая цена'),
        ),
    ]
