# Generated by Django 5.0.1 on 2024-02-13 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('clothes', '0003_clothes_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cloth_category', to='categories.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
